#ifndef INC_TESTER_TESTER_H_
#define INC_TESTER_TESTER_H_

#include "main.h"
#include <stdbool.h>

#define AMP_COUNT	  10
#define DRV_COUNT	  10

#define AMP_T1_ACT_ON	  HAL_GPIO_WritePin(AMP_T1_ACT_GPIO_Port, AMP_T1_ACT_Pin, GPIO_PIN_SET)
#define AMP_T2_ACT_ON	  HAL_GPIO_WritePin(AMP_T2_ACT_GPIO_Port, AMP_T2_ACT_Pin, GPIO_PIN_SET)
#define AMP_T3_ACT_ON	  HAL_GPIO_WritePin(AMP_T3_ACT_GPIO_Port, AMP_T3_ACT_Pin, GPIO_PIN_SET)
#define AMP_T4_ACT_ON	  HAL_GPIO_WritePin(AMP_T4_ACT_GPIO_Port, AMP_T4_ACT_Pin, GPIO_PIN_SET)
#define AMP_T5_ACT_ON	  HAL_GPIO_WritePin(AMP_T5_ACT_GPIO_Port, AMP_T5_ACT_Pin, GPIO_PIN_SET)
#define AMP_T6_ACT_ON	  HAL_GPIO_WritePin(AMP_T6_ACT_GPIO_Port, AMP_T6_ACT_Pin, GPIO_PIN_SET)
#define AMP_T7_ACT_ON	  HAL_GPIO_WritePin(AMP_T7_ACT_GPIO_Port, AMP_T7_ACT_Pin, GPIO_PIN_SET)
#define AMP_T8_ACT_ON	  HAL_GPIO_WritePin(AMP_T8_ACT_GPIO_Port, AMP_T8_ACT_Pin, GPIO_PIN_SET)
#define AMP_T9_ACT_ON	  HAL_GPIO_WritePin(AMP_T9_ACT_GPIO_Port, AMP_T9_ACT_Pin, GPIO_PIN_SET)
#define AMP_T10_ACT_ON	  HAL_GPIO_WritePin(AMP_T10_ACT_GPIO_Port, AMP_T10_ACT_Pin, GPIO_PIN_SET)
#define AMP_T1_ACT_OFF	  HAL_GPIO_WritePin(AMP_T1_ACT_GPIO_Port, AMP_T1_ACT_Pin, GPIO_PIN_RESET)
#define AMP_T2_ACT_OFF	  HAL_GPIO_WritePin(AMP_T2_ACT_GPIO_Port, AMP_T2_ACT_Pin, GPIO_PIN_RESET)
#define AMP_T3_ACT_OFF	  HAL_GPIO_WritePin(AMP_T3_ACT_GPIO_Port, AMP_T3_ACT_Pin, GPIO_PIN_RESET)
#define AMP_T4_ACT_OFF	  HAL_GPIO_WritePin(AMP_T4_ACT_GPIO_Port, AMP_T4_ACT_Pin, GPIO_PIN_RESET)
#define AMP_T5_ACT_OFF	  HAL_GPIO_WritePin(AMP_T5_ACT_GPIO_Port, AMP_T5_ACT_Pin, GPIO_PIN_RESET)
#define AMP_T6_ACT_OFF	  HAL_GPIO_WritePin(AMP_T6_ACT_GPIO_Port, AMP_T6_ACT_Pin, GPIO_PIN_RESET)
#define AMP_T7_ACT_OFF	  HAL_GPIO_WritePin(AMP_T7_ACT_GPIO_Port, AMP_T7_ACT_Pin, GPIO_PIN_RESET)
#define AMP_T8_ACT_OFF	  HAL_GPIO_WritePin(AMP_T8_ACT_GPIO_Port, AMP_T8_ACT_Pin, GPIO_PIN_RESET)
#define AMP_T9_ACT_OFF	  HAL_GPIO_WritePin(AMP_T9_ACT_GPIO_Port, AMP_T9_ACT_Pin, GPIO_PIN_RESET)
#define AMP_T10_ACT_OFF	  HAL_GPIO_WritePin(AMP_T10_ACT_GPIO_Port, AMP_T10_ACT_Pin, GPIO_PIN_RESET)

#define AMP_ON_ACT_ON	  HAL_GPIO_WritePin(AMP_ON_ACT_GPIO_Port, AMP_ON_ACT_Pin, GPIO_PIN_SET)
#define DRV_ON_ACT_ON	  HAL_GPIO_WritePin(DRV_ON_ACT_GPIO_Port, DRV_ON_ACT_Pin, GPIO_PIN_SET)
#define AMP_ON_ACT_OFF	  HAL_GPIO_WritePin(AMP_ON_ACT_GPIO_Port, AMP_ON_ACT_Pin, GPIO_PIN_RESET)
#define DRV_ON_ACT_OFF	  HAL_GPIO_WritePin(DRV_ON_ACT_GPIO_Port, DRV_ON_ACT_Pin, GPIO_PIN_RESET)

#define BAT_OFF_ACT_ON	  HAL_GPIO_WritePin(BAT_OFF_ACT_GPIO_Port, BAT_OFF_ACT_Pin, GPIO_PIN_SET)
#define BAT_MTS_ACT_ON	  HAL_GPIO_WritePin(BAT_MTS_ACT_GPIO_Port, BAT_MTS_ACT_Pin, GPIO_PIN_SET)
#define CU_RESET_ACT_ON	  HAL_GPIO_WritePin(CU_RESET_ACT_GPIO_Port, CU_RESET_ACT_Pin, GPIO_PIN_SET)
#define BAT_OFF_ACT_OFF	  HAL_GPIO_WritePin(BAT_OFF_ACT_GPIO_Port, BAT_OFF_ACT_Pin, GPIO_PIN_RESET)
#define BAT_MTS_ACT_OFF	  HAL_GPIO_WritePin(BAT_MTS_ACT_GPIO_Port, BAT_MTS_ACT_Pin, GPIO_PIN_RESET)
#define CU_RESET_ACT_OFF  HAL_GPIO_WritePin(CU_RESET_ACT_GPIO_Port, CU_RESET_ACT_Pin, GPIO_PIN_RESET)

#define OSC_ON	  	  HAL_GPIO_WritePin(OSC_ON_GPIO_Port, OSC_ON_Pin, GPIO_PIN_SET)
#define OSC_OFF	 	  HAL_GPIO_WritePin(OSC_ON_GPIO_Port, OSC_ON_Pin, GPIO_PIN_RESET)

typedef enum {
  SYSTEM_AMP_T1_ACT,
  SYSTEM_AMP_T2_ACT,
  SYSTEM_AMP_T3_ACT,
  SYSTEM_AMP_T4_ACT,
  SYSTEM_AMP_T5_ACT,
  SYSTEM_AMP_T6_ACT,
  SYSTEM_AMP_T7_ACT,
  SYSTEM_AMP_T8_ACT,
  SYSTEM_AMP_T9_ACT,
  SYSTEM_AMP_T10_ACT,
  SYSTEM_AMP_ON_ACT,
  SYSTEM_DRV_ON_ACT,
  SYSTEM_BAT_OFF_ACT,
  SYSTEM_BAT_MTS_ACT,
  SYSTEM_CU_RESET_ACT
} tester_signals_t;

void tester_init (void);
bool tester_check_amplifier (tester_signals_t n);
bool tester_check_driver (tester_signals_t n);

#endif /* INC_TESTER_TESTER_H_ */
